version: "3.9"

services:
    mysql:
        image: mysql:8.0.31
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
    # mailhog:
    #     build:
    #         dockerfile: ./docker/mailhog/Dockerfile
    #     ports:
    #         - 8025:8025
    #         - 1025:1025

volumes:
    db_data:
